### ISSUE TITLE
Thank you for your project.

### ISSUE THREAD

**Issue by neohusky** [mbuckaway/esp32-homekit-garagedoor#1]
Hi Mark

I just stumbled open your project.  I was ready to do a similar project using a pi which I am comfortable with and have now decided to get my feet wet with ESP32.

I’m being lazy here: Any chance you could post a brief wiring diagram for the esp board, relay board and sensors?

**Comment by mbuckaway** [comment]
I used a RPi with Homebridge for the project the first time around (my code is on another repo here on Github), but running a full linux distro for something that did this one thing was complete overkill, and I had one of the RPI OS updates completely blow away the SDCARD. The ESP32 does this one thing well, and there is no SDCARD to get damaged - nevermind, it's cheaper. It was a great day be able to pull the RPi off the wall of my garage.

The readme.md really does explain the circuit but perhaps needs a bit of verbosity. II used a ESP32 DevKitC v4 from Aliexpress, but you can buy them anywhere. DigiKey has them if you want it tomorrow. There is one switch mounted at the top of the garage door (door open sensor) and one switch near the bottom of the door (door closed sensor). They are wired directly to the associated GPIO on the ESP32 devkit board. No capacitors or resistors are required because switch debounce is done in software. The switches are active low, so the other side of the switches go to ground on the ESP32. I used a reed switch for the top of the door and a magnetic door close switch for the bottom of the door which I found locally at a hobby electronics shop.

The relay board takes another GPIO  - mine is a 5v relay board, so I wired the 5v line to the 5v line on the ESP32, and ground to the ESP32 ground, and the data line to the ESP32 GPIO. Lots of these are on Alliexpress, but my favourite supply shop locally had them.  The other side of the relay board uses the N/O connections to connect to the garage door switch - so it takes the place of a human. I suggest wiring everything on a breadboard first, and get it working. I used a set of dip switches to similar the door switches for testing.

I power the device from the USB port from a cheap USB power supply which is plugged into the wall in my garage.

Hope that is descriptive enough....I may create a circuit diagram at some point. I updated the code a month ago to make it work correctly - and Siri is quite happy to control my garage door from my HomePod or shut the garage door at 11pm should I leave it open.

Enjoy,
Mark

**Comment by neohusky** [comment]
Hey Mark

Thank you for such a detailed explanation of ESP32 circuit. It does seem like a natural evolution from the RPi considering we only require it to do one task. 

I’ve ordered my board and look forward to putting this together over the coming weeks. 

Thanks Heaps,
Theo

**Comment by neohusky** [comment]
G'DAy Mark

I hope you've been safe and well. My components are tricking in.  The only thing I'm missing are the reed switches for the open close sensors.  In any case I've got a testbed and have everything wired and homekit sees my set up.

My question is why would the relay stay permanently energised rather than pulse when I try and open the door using homekit.  I have not yet tried the NO connections yet, but, every time I plug in the data line to the relay I hear it tick and stay engaged (the green light stays permanently on whilst the data line is connected. 

Do you have any suggestions on how to troubleshoot this unexpected behaviour?
![IMG_4605](https://user-images.githubusercontent.com/1212618/111318175-e93b1580-86b8-11eb-8fc1-fa537adf56b5.jpg)

**Comment by mbuckaway** [comment]
I suggestion:
- verify that the setup is correct in the idf menuconfig - set the relay GPIO to the one you use. Unconfigured pins on the ESP32 can have an undefined response
- Use the serial monitor to see what is happen on the ESP32 console
- Use a LED (with say a 100 ohm resistor in series) in place of the relay connected to ground.
- If all else fails, create a simple program that does nothing more than toggle a GPIO - you can hard code everything. There is a GPIO example in the ESP-IDF code you can base it on.

Something to consider is the GPIO's on the ESP32 are 3.3v and have a max output of 40ma. If the relay is expecting 5v logic, it might not work correctly. If the LED works and the relay does not, you'll need to find one that supports a 3.3v input. You can also try driving the relay from the 3.3 power supply if it supports it.

Hope that helps.

**Comment by neohusky** [comment]
Hey Mark

Thanks for the quick response.  I'm using the standard config of GPIOs and the monitor output is below.

I was going to go back to basics and just do a single button project for testing the relay as you suggested, but, thought there might be something else I've missed.

BTW..I tried the 3.3V input with the same response on the relay. 
`I (13555) GDGPIO: Door status check: open=contact not detected - close=contact detected
I (13565) GDGPIO: Reporting door: closed
I (13565) GDGPIO: Kicking the relay...
I (13605) BUTTON: 25 LONG
I (13655) BUTTON: 25 LONG
I (13705) BUTTON: 25 LONG
I (13755) BUTTON: 25 LONG
I (13805) BUTTON: 25 LONG
I (13855) BUTTON: 25 LONG
I (13905) BUTTON: 25 LONG
I (13955) BUTTON: 25 LONG`

<img width="796" alt="Screen Shot 2021-03-17 at 12 57 23 am" src="https://user-images.githubusercontent.com/1212618/111321111-bfcfb900-86bb-11eb-9785-cc79f6ca7348.png">
